//! Activation script generation for bundles
//!
//! Generates portable activation scripts that use relative paths.

use super::BundleLayout;
use crate::error::{MsvcKitError, Result};

/// Generated bundle scripts
#[derive(Debug, Clone)]
pub struct BundleScripts {
    /// CMD activation script content
    pub cmd: String,
    /// PowerShell activation script content
    pub powershell: String,
    /// Bash activation script content
    pub bash: String,
}

/// Generate activation scripts for a bundle
///
/// Creates portable scripts that use relative paths so the bundle
/// can be moved to any location.
pub fn generate_bundle_scripts(layout: &BundleLayout) -> Result<BundleScripts> {
    let cmd = generate_cmd_script(layout)?;
    let powershell = generate_powershell_script(layout)?;
    let bash = generate_bash_script(layout)?;

    Ok(BundleScripts {
        cmd,
        powershell,
        bash,
    })
}

/// Save bundle scripts to the bundle directory
pub async fn save_bundle_scripts(layout: &BundleLayout, scripts: &BundleScripts) -> Result<()> {
    let cmd_path = layout.root.join("setup.bat");
    let ps_path = layout.root.join("setup.ps1");
    let bash_path = layout.root.join("setup.sh");

    tokio::fs::write(&cmd_path, &scripts.cmd)
        .await
        .map_err(|e| MsvcKitError::Io(e))?;
    tokio::fs::write(&ps_path, &scripts.powershell)
        .await
        .map_err(|e| MsvcKitError::Io(e))?;
    tokio::fs::write(&bash_path, &scripts.bash)
        .await
        .map_err(|e| MsvcKitError::Io(e))?;

    Ok(())
}

/// Generate CMD batch script
fn generate_cmd_script(layout: &BundleLayout) -> Result<String> {
    let msvc_ver = &layout.msvc_version;
    let sdk_ver = &layout.sdk_version;
    let arch = layout.arch.to_string();
    let host_arch = layout.host_arch.msvc_host_dir();
    let target_arch = layout.arch.msvc_target_dir();

    let script = format!(
        r#"@echo off
REM Portable MSVC Toolchain Activation Script
REM Generated by msvc-kit
REM MSVC: {msvc_ver}, SDK: {sdk_ver}, Arch: {arch}

setlocal enabledelayedexpansion

REM Get the directory where this script is located
set "BUNDLE_ROOT=%~dp0"
REM Remove trailing backslash
if "%BUNDLE_ROOT:~-1%"=="\" set "BUNDLE_ROOT=%BUNDLE_ROOT:~0,-1%"

REM VC paths
set "VCINSTALLDIR=%BUNDLE_ROOT%\VC"
set "VCToolsInstallDir=%BUNDLE_ROOT%\VC\Tools\MSVC\{msvc_ver}"
set "VCToolsVersion={msvc_ver}"

REM SDK paths
set "WindowsSdkDir=%BUNDLE_ROOT%\Windows Kits\10"
set "WindowsSDKVersion={sdk_ver}\"
set "WindowsSdkBinPath=%BUNDLE_ROOT%\Windows Kits\10\bin\{sdk_ver}"

REM INCLUDE paths
set "INCLUDE=%BUNDLE_ROOT%\VC\Tools\MSVC\{msvc_ver}\include"
set "INCLUDE=%INCLUDE%;%BUNDLE_ROOT%\Windows Kits\10\Include\{sdk_ver}\ucrt"
set "INCLUDE=%INCLUDE%;%BUNDLE_ROOT%\Windows Kits\10\Include\{sdk_ver}\shared"
set "INCLUDE=%INCLUDE%;%BUNDLE_ROOT%\Windows Kits\10\Include\{sdk_ver}\um"
set "INCLUDE=%INCLUDE%;%BUNDLE_ROOT%\Windows Kits\10\Include\{sdk_ver}\winrt"
set "INCLUDE=%INCLUDE%;%BUNDLE_ROOT%\Windows Kits\10\Include\{sdk_ver}\cppwinrt"

REM LIB paths
set "LIB=%BUNDLE_ROOT%\VC\Tools\MSVC\{msvc_ver}\lib\{arch}"
set "LIB=%LIB%;%BUNDLE_ROOT%\Windows Kits\10\Lib\{sdk_ver}\ucrt\{arch}"
set "LIB=%LIB%;%BUNDLE_ROOT%\Windows Kits\10\Lib\{sdk_ver}\um\{arch}"

REM PATH additions
set "PATH=%BUNDLE_ROOT%\VC\Tools\MSVC\{msvc_ver}\bin\{host_arch}\{target_arch};%PATH%"
set "PATH=%BUNDLE_ROOT%\Windows Kits\10\bin\{sdk_ver}\{arch};%PATH%"

REM Platform info
set "Platform={arch}"
set "VSCMD_ARG_HOST_ARCH={arch}"
set "VSCMD_ARG_TGT_ARCH={arch}"

REM End local and export variables
endlocal & (
    set "VCINSTALLDIR=%VCINSTALLDIR%"
    set "VCToolsInstallDir=%VCToolsInstallDir%"
    set "VCToolsVersion=%VCToolsVersion%"
    set "WindowsSdkDir=%WindowsSdkDir%"
    set "WindowsSDKVersion=%WindowsSDKVersion%"
    set "WindowsSdkBinPath=%WindowsSdkBinPath%"
    set "INCLUDE=%INCLUDE%"
    set "LIB=%LIB%"
    set "PATH=%PATH%"
    set "Platform=%Platform%"
    set "VSCMD_ARG_HOST_ARCH=%VSCMD_ARG_HOST_ARCH%"
    set "VSCMD_ARG_TGT_ARCH=%VSCMD_ARG_TGT_ARCH%"
)

echo MSVC Toolchain activated (MSVC {msvc_ver}, SDK {sdk_ver}, {arch})
"#
    );

    Ok(script)
}

/// Generate PowerShell script
fn generate_powershell_script(layout: &BundleLayout) -> Result<String> {
    let msvc_ver = &layout.msvc_version;
    let sdk_ver = &layout.sdk_version;
    let arch = layout.arch.to_string();
    let host_arch = layout.host_arch.msvc_host_dir();
    let target_arch = layout.arch.msvc_target_dir();

    let script = format!(
        r#"# Portable MSVC Toolchain Activation Script
# Generated by msvc-kit
# MSVC: {msvc_ver}, SDK: {sdk_ver}, Arch: {arch}

# Get the directory where this script is located
$BundleRoot = $PSScriptRoot

# VC paths
$env:VCINSTALLDIR = "$BundleRoot\VC"
$env:VCToolsInstallDir = "$BundleRoot\VC\Tools\MSVC\{msvc_ver}"
$env:VCToolsVersion = "{msvc_ver}"

# SDK paths
$env:WindowsSdkDir = "$BundleRoot\Windows Kits\10"
$env:WindowsSDKVersion = "{sdk_ver}\"
$env:WindowsSdkBinPath = "$BundleRoot\Windows Kits\10\bin\{sdk_ver}"

# INCLUDE paths
$env:INCLUDE = @(
    "$BundleRoot\VC\Tools\MSVC\{msvc_ver}\include",
    "$BundleRoot\Windows Kits\10\Include\{sdk_ver}\ucrt",
    "$BundleRoot\Windows Kits\10\Include\{sdk_ver}\shared",
    "$BundleRoot\Windows Kits\10\Include\{sdk_ver}\um",
    "$BundleRoot\Windows Kits\10\Include\{sdk_ver}\winrt",
    "$BundleRoot\Windows Kits\10\Include\{sdk_ver}\cppwinrt"
) -join ";"

# LIB paths
$env:LIB = @(
    "$BundleRoot\VC\Tools\MSVC\{msvc_ver}\lib\{arch}",
    "$BundleRoot\Windows Kits\10\Lib\{sdk_ver}\ucrt\{arch}",
    "$BundleRoot\Windows Kits\10\Lib\{sdk_ver}\um\{arch}"
) -join ";"

# PATH additions
$NewPaths = @(
    "$BundleRoot\VC\Tools\MSVC\{msvc_ver}\bin\{host_arch}\{target_arch}",
    "$BundleRoot\Windows Kits\10\bin\{sdk_ver}\{arch}"
) -join ";"
$env:PATH = "$NewPaths;$env:PATH"

# Platform info
$env:Platform = "{arch}"
$env:VSCMD_ARG_HOST_ARCH = "{arch}"
$env:VSCMD_ARG_TGT_ARCH = "{arch}"

Write-Host "MSVC Toolchain activated (MSVC {msvc_ver}, SDK {sdk_ver}, {arch})"
"#
    );

    Ok(script)
}

/// Generate Bash script (for WSL/Git Bash)
fn generate_bash_script(layout: &BundleLayout) -> Result<String> {
    let msvc_ver = &layout.msvc_version;
    let sdk_ver = &layout.sdk_version;
    let arch = layout.arch.to_string();
    let host_arch = layout.host_arch.msvc_host_dir();
    let target_arch = layout.arch.msvc_target_dir();

    let script = format!(
        r#"#!/bin/bash
# Portable MSVC Toolchain Activation Script
# Generated by msvc-kit
# MSVC: {msvc_ver}, SDK: {sdk_ver}, Arch: {arch}

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

# Convert to Windows path if running under WSL
if command -v wslpath &> /dev/null; then
    BUNDLE_ROOT=$(wslpath -w "$SCRIPT_DIR")
else
    BUNDLE_ROOT="$SCRIPT_DIR"
fi

# VC paths
export VCINSTALLDIR="$BUNDLE_ROOT/VC"
export VCToolsInstallDir="$BUNDLE_ROOT/VC/Tools/MSVC/{msvc_ver}"
export VCToolsVersion="{msvc_ver}"

# SDK paths
export WindowsSdkDir="$BUNDLE_ROOT/Windows Kits/10"
export WindowsSDKVersion="{sdk_ver}\\"
export WindowsSdkBinPath="$BUNDLE_ROOT/Windows Kits/10/bin/{sdk_ver}"

# INCLUDE paths
export INCLUDE="$BUNDLE_ROOT/VC/Tools/MSVC/{msvc_ver}/include"
export INCLUDE="$INCLUDE;$BUNDLE_ROOT/Windows Kits/10/Include/{sdk_ver}/ucrt"
export INCLUDE="$INCLUDE;$BUNDLE_ROOT/Windows Kits/10/Include/{sdk_ver}/shared"
export INCLUDE="$INCLUDE;$BUNDLE_ROOT/Windows Kits/10/Include/{sdk_ver}/um"
export INCLUDE="$INCLUDE;$BUNDLE_ROOT/Windows Kits/10/Include/{sdk_ver}/winrt"
export INCLUDE="$INCLUDE;$BUNDLE_ROOT/Windows Kits/10/Include/{sdk_ver}/cppwinrt"

# LIB paths
export LIB="$BUNDLE_ROOT/VC/Tools/MSVC/{msvc_ver}/lib/{arch}"
export LIB="$LIB;$BUNDLE_ROOT/Windows Kits/10/Lib/{sdk_ver}/ucrt/{arch}"
export LIB="$LIB;$BUNDLE_ROOT/Windows Kits/10/Lib/{sdk_ver}/um/{arch}"

# PATH additions
export PATH="$BUNDLE_ROOT/VC/Tools/MSVC/{msvc_ver}/bin/{host_arch}/{target_arch}:$PATH"
export PATH="$BUNDLE_ROOT/Windows Kits/10/bin/{sdk_ver}/{arch}:$PATH"

# Platform info
export Platform="{arch}"
export VSCMD_ARG_HOST_ARCH="{arch}"
export VSCMD_ARG_TGT_ARCH="{arch}"

echo "MSVC Toolchain activated (MSVC {msvc_ver}, SDK {sdk_ver}, {arch})"
"#
    );

    Ok(script)
}

/// Generate README for the bundle
pub fn generate_bundle_readme(layout: &BundleLayout) -> String {
    format!(
        r#"Portable MSVC Toolchain Bundle
==============================

MSVC Version:        {}
Windows SDK Version: {}
Architecture:        {}

Contents:
- setup.bat        : CMD activation script
- setup.ps1        : PowerShell activation script
- setup.sh         : Bash/WSL activation script
- VC/              : Visual C++ compiler and libraries
- Windows Kits/    : Windows SDK

Usage:
1. Extract this bundle to your desired location
2. Run the appropriate setup script for your shell:
   - CMD:        setup.bat
   - PowerShell: .\setup.ps1
   - Bash/WSL:   source setup.sh
3. cl, link, nmake, and other MSVC tools become available

Directory Structure:
- VC/Tools/MSVC/{}/bin/...  : Compiler binaries (cl.exe, link.exe)
- VC/Tools/MSVC/{}/include/ : C++ headers
- VC/Tools/MSVC/{}/lib/     : Static libraries
- Windows Kits/10/Include/  : Windows SDK headers
- Windows Kits/10/Lib/      : Windows SDK libraries
- Windows Kits/10/bin/      : SDK tools (rc.exe)

License Notice:
The MSVC compiler and Windows SDK included in this bundle are
property of Microsoft and subject to Microsoft Visual Studio
License Terms: https://visualstudio.microsoft.com/license-terms/

This bundle was created for personal/development use. Microsoft
software components are NOT covered by msvc-kit's MIT license.
"#,
        layout.msvc_version,
        layout.sdk_version,
        layout.arch,
        layout.msvc_version,
        layout.msvc_version,
        layout.msvc_version,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::version::Architecture;
    use std::path::PathBuf;

    fn sample_layout() -> BundleLayout {
        BundleLayout {
            root: PathBuf::from("C:/msvc-bundle"),
            msvc_version: "14.44.34823".to_string(),
            sdk_version: "10.0.26100.0".to_string(),
            arch: Architecture::X64,
            host_arch: Architecture::X64,
        }
    }

    #[test]
    fn test_generate_cmd_script() {
        let layout = sample_layout();
        let script = generate_cmd_script(&layout).unwrap();

        assert!(script.contains("BUNDLE_ROOT=%~dp0"));
        assert!(script.contains("14.44.34823"));
        assert!(script.contains("10.0.26100.0"));
        assert!(script.contains("Hostx64"));
    }

    #[test]
    fn test_generate_powershell_script() {
        let layout = sample_layout();
        let script = generate_powershell_script(&layout).unwrap();

        assert!(script.contains("$PSScriptRoot"));
        assert!(script.contains("14.44.34823"));
        assert!(script.contains("10.0.26100.0"));
    }

    #[test]
    fn test_generate_bash_script() {
        let layout = sample_layout();
        let script = generate_bash_script(&layout).unwrap();

        assert!(script.contains("BASH_SOURCE"));
        assert!(script.contains("14.44.34823"));
        assert!(script.contains("10.0.26100.0"));
    }
}
