//! Execute a command in a selected toolchain without changing the parent environment.

use std::ffi::{OsStr, OsString};
use std::process::{Command, ExitStatus};

use crate::{get_env_vars, MsvcEnvironment, MsvcKitError, Result};

/// Apply toolchain variables, preserving the inherited PATH after the selected tools.
pub fn configure_command(command: &mut Command, environment: &MsvcEnvironment) -> Result<()> {
    let mut variables = get_env_vars(environment);
    variables.remove("PATH");
    command.envs(variables);
    let mut paths = environment.bin_paths.clone();
    if let Some(inherited) = std::env::var_os("PATH") {
        paths.extend(std::env::split_paths(&inherited));
    }
    let path = std::env::join_paths(paths)
        .map_err(|error| MsvcKitError::EnvSetup(format!("Cannot construct PATH: {error}")))?;
    command.env("PATH", path);
    Ok(())
}

/// Run a child process with inherited standard streams and preserve its exit status.
pub fn run_in_toolchain(
    environment: &MsvcEnvironment,
    program: &OsStr,
    arguments: &[OsString],
) -> Result<ExitStatus> {
    let mut command = Command::new(program);
    command.args(arguments);
    configure_command(&mut command, environment)?;
    command.status().map_err(MsvcKitError::from)
}

/// Emit a CMake toolchain for Ninja. Invoke CMake through `run` to supply INCLUDE/LIB.
pub fn write_cmake_toolchain(
    environment: &MsvcEnvironment,
    output: &std::path::Path,
) -> Result<()> {
    fn literal(path: &std::path::Path) -> String {
        let value = path.to_string_lossy().replace('\\', "/");
        let mut equals = String::new();
        while value.contains(&format!("]{equals}]")) {
            equals.push('=');
        }
        format!("[{equals}[{value}]{equals}]")
    }
    let tools = environment.tool_paths();
    let required = |path: Option<std::path::PathBuf>, name: &str| {
        path.ok_or_else(|| {
            MsvcKitError::ComponentNotFound(format!("Required tool {name} is missing"))
        })
    };
    let cl = required(tools.cl, "cl.exe")?;
    let linker = required(tools.link, "link.exe")?;
    let librarian = required(tools.lib, "lib.exe")?;
    let mut content = format!(
        "# Generated by msvc-kit; use the Ninja generator inside msvc-kit run.\n# Fingerprint: {}\nset(CMAKE_SYSTEM_NAME Windows)\nset(CMAKE_SYSTEM_PROCESSOR {})\nset(CMAKE_C_COMPILER {})\nset(CMAKE_CXX_COMPILER {})\nset(CMAKE_LINKER {})\nset(CMAKE_AR {})\n",
        environment.fingerprint(), environment.arch,
        literal(&cl), literal(&cl), literal(&linker), literal(&librarian)
    );
    if let Some(rc) = tools.rc {
        content.push_str(&format!("set(CMAKE_RC_COMPILER {})\n", literal(&rc)));
    }
    if let Some(mt) = tools.mt {
        content.push_str(&format!("set(CMAKE_MT {})\n", literal(&mt)));
    }
    crate::storage::atomic_write(output, content.as_bytes())
}
